apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  application.firstName: "VismarkFromKubernetesConfigMap"
  application.lastName: "JuarezFromKubernetesConfigMap"
  application.age: "30"
